      - pytorch_ios_build:
          build_environment: pytorch-ios-11.2.1-x86_64_build
          ios_arch: x86_64
          ios_platform: SIMULATOR
          name: pytorch_ios_11_2_1_x86_64_build
          requires:
            - setup
      - pytorch_ios_build:
          build_environment: pytorch-ios-11.2.1-arm64_build
          context: org-member
          ios_arch: arm64
          ios_platform: OS
          name: pytorch_ios_11_2_1_arm64_build
          requires:
            - setup
      - pytorch_ios_build:
          build_environment: pytorch-ios-11.2.1-arm64_custom_build
          context: org-member
          ios_arch: arm64
          ios_platform: OS
          name: pytorch_ios_11_2_1_arm64_custom_build
          op_list: mobilenetv2.yaml
          requires:
            - setup
