      - binary_ios_build:
          build_environment: libtorch-ios-11.2.1-nightly-x86_64-build
          context: org-member
          filters:
            branches:
              only: nightly
          ios_arch: x86_64
          ios_platform: SIMULATOR
          name: pytorch_ios_11_2_1_nightly_x86_64_build
          requires:
            - setup
      - binary_ios_build:
          build_environment: libtorch-ios-11.2.1-nightly-arm64-build
          context: org-member
          filters:
            branches:
              only: nightly
          ios_arch: arm64
          ios_platform: OS
          name: pytorch_ios_11_2_1_nightly_arm64_build
          requires:
            - setup
      - binary_ios_upload:
          build_environment: libtorch-ios-11.2.1-nightly-binary-build-upload
          context: org-member
          filters:
            branches:
              only: nightly
          requires:
            - setup
            - pytorch_ios_11_2_1_nightly_x86_64_build
            - pytorch_ios_11_2_1_nightly_arm64_build
