      # TODO: Refactor circleci/cimodel/data/binary_build_data.py to generate this file
      #       instead of doing one offs here
      # Binary builds (subset, to smoke test that they'll work)
      #
      # NB: If you modify this file, you need to also modify
      # the binary_and_smoke_tests_on_pr variable in
      # pytorch-ci-hud to adjust the list of whitelisted builds
      # at https://github.com/ezyang/pytorch-ci-hud/blob/master/src/BuildHistoryDisplay.js
      #
      # Note:
      # This binary build is currently broken, see https://github_com/pytorch/pytorch/issues/16710
      # - binary_linux_conda_3_6_cu90_devtoolset7_build
      # - binary_linux_conda_3_6_cu90_devtoolset7_test
      #
      # TODO
      # we should test a libtorch cuda build, but they take too long
      # - binary_linux_libtorch_3_6m_cu90_devtoolset7_static-without-deps_build
      - binary_linux_build:
          build_environment: manywheel 3.7m cu102 devtoolset7
          docker_image: pytorch/manylinux-cuda102
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          name: binary_linux_manywheel_3_7m_cu102_devtoolset7_build
          requires:
            - setup
      - binary_linux_build:
          build_environment: libtorch 3.7m cpu devtoolset7
          docker_image: pytorch/manylinux-cuda102
          libtorch_variant: shared-with-deps
          name: binary_linux_libtorch_3_7m_cpu_devtoolset7_shared-with-deps_build
          requires:
            - setup
      - binary_linux_build:
          build_environment: libtorch 3.7m cpu gcc5.4_cxx11-abi
          docker_image: pytorch/pytorch-binary-docker-image-ubuntu16.04:latest
          libtorch_variant: shared-with-deps
          name: binary_linux_libtorch_3_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_build
          requires:
            - setup
      - binary_mac_build:
          build_environment: wheel 3.7 cpu
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          name: binary_macos_wheel_3_7_cpu_build
          requires:
            - setup
      - binary_mac_build:
          # This job has an average run time of 3 hours o.O
          # Now only running this on master to reduce overhead
          build_environment: libtorch 3.7 cpu
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          name: binary_macos_libtorch_3_7_cpu_build
          requires:
            - setup
      - binary_windows_build:
          build_environment: libtorch 3.7 cpu debug
          name: binary_windows_libtorch_3_7_cpu_debug_build
          requires:
            - setup
      - binary_windows_build:
          build_environment: libtorch 3.7 cpu release
          name: binary_windows_libtorch_3_7_cpu_release_build
          requires:
            - setup
      - binary_windows_build:
          build_environment: wheel 3.7 cu102
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          name: binary_windows_wheel_3_7_cu102_build
          requires:
            - setup
      - binary_linux_test:
          build_environment: manywheel 3.7m cu102 devtoolset7
          docker_image: pytorch/manylinux-cuda102
          filters:
            branches:
              only:
                - master
                - /ci-all\/.*/
                - /release\/.*/
          name: binary_linux_manywheel_3_7m_cu102_devtoolset7_test
          requires:
            - setup
            - binary_linux_manywheel_3_7m_cu102_devtoolset7_build
          resource_class: gpu.medium
          use_cuda_docker_runtime: "1"
      - binary_linux_test:
          build_environment: libtorch 3.7m cpu devtoolset7
          docker_image: pytorch/manylinux-cuda102
          libtorch_variant: shared-with-deps
          name: binary_linux_libtorch_3_7m_cpu_devtoolset7_shared-with-deps_test
          requires:
            - setup
            - binary_linux_libtorch_3_7m_cpu_devtoolset7_shared-with-deps_build
      - binary_linux_test:
          build_environment: libtorch 3.7m cpu gcc5.4_cxx11-abi
          docker_image: pytorch/pytorch-binary-docker-image-ubuntu16.04:latest
          libtorch_variant: shared-with-deps
          name: binary_linux_libtorch_3_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_test
          requires:
            - setup
            - binary_linux_libtorch_3_7m_cpu_gcc5_4_cxx11-abi_shared-with-deps_build
