      - pytorch_linux_build:
          build_environment: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-x86_32
          docker_image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:9a3986fa-7ce7-4a36-a001-3c9bef9892e2
          filters:
            branches:
              only: nightly
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
          requires:
            - setup
      - pytorch_linux_build:
          build_environment: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-x86_64
          docker_image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:9a3986fa-7ce7-4a36-a001-3c9bef9892e2
          filters:
            branches:
              only: nightly
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
          requires:
            - setup
      - pytorch_linux_build:
          build_environment: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-arm-v7a
          docker_image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:9a3986fa-7ce7-4a36-a001-3c9bef9892e2
          filters:
            branches:
              only: nightly
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
          requires:
            - setup
      - pytorch_linux_build:
          build_environment: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-arm-v8a
          docker_image: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:9a3986fa-7ce7-4a36-a001-3c9bef9892e2
          filters:
            branches:
              only: nightly
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build
          requires:
            - setup
      - pytorch_android_gradle_build:
          filters:
            branches:
              only: nightly
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_android_gradle_build
          requires:
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_build
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_64_build
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v7a_build
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_arm_v8a_build
      - pytorch_android_publish_snapshot:
          context: org-member
          filters:
            branches:
              only: nightly
          name: nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_x86_32_android_publish_snapshot
          requires:
            - nightly_pytorch_linux_xenial_py3_clang5_android_ndk_r19c_android_gradle_build
